
# Do NOT edit this file. Instead, just call it from the command line,
# using the instructions in the assignment notebook.

import sys
questions = sys.argv[1:]


valid_ids = ['q1', 'q2', 'q3']
break_flag = False
invalid_ids = []
for question in questions:
    if question != 'all' and question not in valid_ids:
        invalid_ids.append(question)

if len(invalid_ids) > 0:
    print(str(invalid_ids) + ' is/are not a valid question number(s). The possible question numbers are ' + str(valid_ids) + '.')
    sys.exit()

# Initialize Otter
import otter
grader = otter.Notebook("lab.ipynb")

# %load_ext autoreload
# %autoreload 2

from lab import *

import pandas as pd
import numpy as np
np.set_printoptions(legacy='1.21')
import os
import re

if 'q1' in questions or questions == [] or 'all' in questions:
    print(grader.check("q1"))

# experiment with extract_personal using the file s below
fp = os.path.join('data', 'messy.txt')
s = open(fp, encoding='utf8').read()

# don't change this cell, but do run it -- it is needed for the tests
test_fp = os.path.join('data', 'messy.test.txt')
test_s = open(test_fp, encoding='utf8').read()
emails, ssn, bitcoin, addresses = extract_personal(test_s)

if 'q2' in questions or questions == [] or 'all' in questions:
    print(grader.check("q2"))

# The public tests don't test your work on the `ira` data,
# but the hidden tests do.
# So, make sure to thoroughly test your work yourself!
fp = os.path.join('data', 'ira.csv')
ira = pd.read_csv(fp, names=['id', 'name', 'date', 'text'])

# don't change this cell, but do run it -- it is needed for the tests
fp_test = 'data/ira_test.csv'
ira_test = pd.read_csv(fp_test, header=None)
text_test = ira_test.iloc[:, -1:]
text_test.columns = ['text']
feature_test = create_features(text_test)

if 'q3' in questions or questions == [] or 'all' in questions:
    print(grader.check("q3"))


